<?php

namespace Database\Seeders;

use App\Models\Package;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class PackageSeeder extends Seeder
{
    public function run()
    {
        Package::create([
            'webshopName' => 'Sport World',
            'webshopStreet' => 'Marie Heinekenplein',
            'webshopHousenumber' => 5,
            'webshopZipcode' => '4551VK',
            'webshopCity' => 'Rotterdam',
            'customerName' => 'Arie Kassa',
            'customerEmail' => 'arie@kassa.nl',
            'customerStreet' => 'Kerkstraat',
            'customerHousenumber' => 10,
            'customerZipcode' => '4867GS',
            'customerCity' => 'Amsterdam',
            'status' => 'Submitted',
            'dimensions' => '40x70x30',
            'weight' => '1500',
            'trackandtracecode' => Str::random(20),
        ]);

        Package::create([
            'webshopName' => 'Sport World',
            'webshopStreet' => 'Marie Heinekenplein',
            'webshopHousenumber' => 5,
            'webshopZipcode' => '4551VK',
            'webshopCity' => 'Rotterdam',
            'customerName' => 'Emily Johnson',
            'customerEmail' => 'emily.johnson@email.com',
            'customerStreet' => 'Zijlstraat',
            'customerHousenumber' => 8,
            'customerZipcode' => '7655YU',
            'customerCity' => 'Haarlem',
            'status' => 'Submitted',
            'dimensions' => '20x90x20',
            'weight' => '1800',
            'trackandtracecode' => Str::random(20),
        ]);

        Package::create([
            'webshopName' => 'Sport World',
            'webshopStreet' => 'Marie Heinekenplein',
            'webshopHousenumber' => 5,
            'webshopZipcode' => '4551VK',
            'webshopCity' => 'Rotterdam',
            'customerName' => 'Jacob Smith',
            'customerEmail' => 'jacob.smith@email.com',
            'customerStreet' => 'Kalverstraat',
            'customerHousenumber' => 14,
            'customerZipcode' => '1615CH',
            'customerCity' => 'Amsterdam',
            'status' => 'Submitted',
            'dimensions' => '20x10x20',
            'weight' => '300',
            'trackandtracecode' => Str::random(20),
        ]);

        Package::create([
            'webshopName' => 'Sport World',
            'webshopStreet' => 'Marie Heinekenplein',
            'webshopHousenumber' => 5,
            'webshopZipcode' => '4551VK',
            'webshopCity' => 'Rotterdam',
            'customerName' => 'Olivia Brown',
            'customerEmail' => 'olivia.brown@email.com',
            'customerStreet' => 'Keizersgracht',
            'customerHousenumber' => 44,
            'customerZipcode' => '5456HK',
            'customerCity' => 'Amsterdam',
            'status' => 'Submitted',
            'dimensions' => '80x60x40',
            'weight' => '1200',
            'trackandtracecode' => Str::random(20),
        ]);

        Package::create([
            'webshopName' => 'Sport World',
            'webshopStreet' => 'Marie Heinekenplein',
            'webshopHousenumber' => 5,
            'webshopZipcode' => '4551VK',
            'webshopCity' => 'Rotterdam',
            'customerName' => 'Ethan Davis',
            'customerEmail' => 'ethan.davis@email.com',
            'customerStreet' => 'Grote Marktstraat',
            'customerHousenumber' => 20,
            'customerZipcode' => '4798VB',
            'customerCity' => 'Den Haag',
            'status' => 'Submitted',
            'dimensions' => '30x20x60',
            'weight' => '900',
            'trackandtracecode' => Str::random(20),
        ]);

        Package::create([
            'webshopName' => 'Sport World',
            'webshopStreet' => 'Marie Heinekenplein',
            'webshopHousenumber' => 5,
            'webshopZipcode' => '4551VK',
            'webshopCity' => 'Rotterdam',
            'customerName' => 'Ava Wilson',
            'customerEmail' => 'ava.wilson@email.com',
            'customerStreet' => 'Prins Hendrikstraat',
            'customerHousenumber' => 8,
            'customerZipcode' => '7890KL',
            'customerCity' => 'Amersfoort',
            'status' => 'Submitted',
            'dimensions' => '100x80x60',
            'weight' => '2500',
            'trackandtracecode' => Str::random(20),
        ]);

        Package::create([
            'webshopName' => 'Sport World',
            'webshopStreet' => 'Marie Heinekenplein',
            'webshopHousenumber' => 5,
            'webshopZipcode' => '4551VK',
            'webshopCity' => 'Rotterdam',
            'customerName' => 'William Jones',
            'customerEmail' => 'william.jones@email.com',
            'customerStreet' => 'Dijkweg',
            'customerHousenumber' => 23,
            'customerZipcode' => '4567LM',
            'customerCity' => 'Hoek van Holland',
            'status' => 'Submitted',
            'dimensions' => '90x60x50',
            'weight' => '1800',
            'trackandtracecode' => Str::random(20),
        ]);

        Package::create([
            'webshopName' => 'Sport World',
            'webshopStreet' => 'Marie Heinekenplein',
            'webshopHousenumber' => 5,
            'webshopZipcode' => '4551VK',
            'webshopCity' => 'Rotterdam',
            'customerName' => 'Sophia Martin',
            'customerEmail' => 'sophia.martin@email.com',
            'customerStreet' => 'Goudkade',
            'customerHousenumber' => 10,
            'customerZipcode' => '6789NO',
            'customerCity' => 'Gouda',
            'status' => 'Submitted',
            'dimensions' => '120x80x40',
            'weight' => '3000',
            'trackandtracecode' => Str::random(20),
        ]);

        Package::create([
            'webshopName' => 'Sport World',
            'webshopStreet' => 'Marie Heinekenplein',
            'webshopHousenumber' => 5,
            'webshopZipcode' => '4551VK',
            'webshopCity' => 'Rotterdam',
            'customerName' => 'Benjamin Lee',
            'customerEmail' => 'benjamin.lee@email.com',
            'customerStreet' => 'Dennenlaan',
            'customerHousenumber' => 21,
            'customerZipcode' => '5678PQ',
            'customerCity' => 'Nuenen',
            'status' => 'Submitted',
            'dimensions' => '60x60x60',
            'weight' => '1400',
            'trackandtracecode' => Str::random(20),
        ]);

        Package::create([
            'webshopName' => 'Sport World',
            'webshopStreet' => 'Marie Heinekenplein',
            'webshopHousenumber' => 5,
            'webshopZipcode' => '4551VK',
            'webshopCity' => 'Rotterdam',
            'customerName' => 'Mia Garcia',
            'customerEmail' => 'mia.garcia@email.com',
            'customerStreet' => 'Havenkade',
            'customerHousenumber' => 12,
            'customerZipcode' => '7890RS',
            'customerCity' => 'Kampen',
            'status' => 'Submitted',
            'dimensions' => '70x50x40',
            'weight' => '900',
            'trackandtracecode' => Str::random(20),
        ]);

        Package::create([
            'webshopName' => 'Sport World',
            'webshopStreet' => 'Marie Heinekenplein',
            'webshopHousenumber' => 5,
            'webshopZipcode' => '4551VK',
            'webshopCity' => 'Rotterdam',
            'customerName' => 'Samuel Anderson',
            'customerEmail' => 'samuel.anderson@email.com',
            'customerStreet' => 'Oudezijds Achterburgwal',
            'customerHousenumber' => 23,
            'customerZipcode' => '5678CD',
            'customerCity' => 'Utrecht',
            'status' => 'Submitted',
            'dimensions' => '50x40x30',
            'weight' => '1000',
            'trackandtracecode' => Str::random(20),
        ]);

        Package::create([
            'webshopName' => 'Sport World',
            'webshopStreet' => 'Marie Heinekenplein',
            'webshopHousenumber' => 5,
            'webshopZipcode' => '4551VK',
            'webshopCity' => 'Rotterdam',
            'customerName' => 'Charlotte Hernandez',
            'customerEmail' => 'charlotte.hernandez@email.com',
            'customerStreet' => 'Nieuwezijds Voorburgwal',
            'customerHousenumber' => 12,
            'customerZipcode' => '6789GH',
            'customerCity' => 'Den Haag',
            'status' => 'Submitted',
            'dimensions' => '80x60x40',
            'weight' => '1500',
            'trackandtracecode' => Str::random(20),
        ]);

        Package::create([
            'webshopName' => 'Books Galore',
            'webshopStreet' => 'Lange Poten',
            'webshopHousenumber' => 11,
            'webshopZipcode' => '7994CS',
            'webshopCity' => 'Groningen',
            'customerName' => 'Michael Miller',
            'customerEmail' => 'michael.miller@email.com',
            'customerStreet' => 'Binnenhof',
            'customerHousenumber' => 8,
            'customerZipcode' => '7890KL',
            'customerCity' => 'Amersfoort',
            'status' => 'Submitted',
            'dimensions' => '100x80x60',
            'weight' => '2500',
            'trackandtracecode' => Str::random(20),
        ]);

        Package::create([
            'webshopName' => 'Books Galore',
            'webshopStreet' => 'Lange Poten',
            'webshopHousenumber' => 11,
            'webshopZipcode' => '7994CS',
            'webshopCity' => 'Groningen',
            'customerName' => 'Amelia Martinez',
            'customerEmail' => 'amelia.martinez@email.com',
            'customerStreet' => 'Stationsstraat',
            'customerHousenumber' => 5,
            'customerZipcode' => '6789HI',
            'customerCity' => 'Utrecht',
            'status' => 'Submitted',
            'dimensions' => '60x40x20',
            'weight' => '2000',
            'trackandtracecode' => Str::random(20),
        ]);

        Package::create([
            'webshopName' => 'Books Galore',
            'webshopStreet' => 'Lange Poten',
            'webshopHousenumber' => 11,
            'webshopZipcode' => '7994CS',
            'webshopCity' => 'Groningen',
            'customerName' => 'James Davis',
            'customerEmail' => 'james.davis@email.com',
            'customerStreet' => 'Oudegracht',
            'customerHousenumber' => 14,
            'customerZipcode' => '7890LM',
            'customerCity' => 'Den Haag',
            'status' => 'Submitted',
            'dimensions' => '70x50x30',
            'weight' => '1200',
            'trackandtracecode' => Str::random(20),
        ]);

        Package::create([
            'webshopName' => 'Books Galore',
            'webshopStreet' => 'Lange Poten',
            'webshopHousenumber' => 11,
            'webshopZipcode' => '7994CS',
            'webshopCity' => 'Groningen',
            'customerName' => 'Isabella Johnson',
            'customerEmail' => 'isabella.johnson@email.com',
            'customerStreet' => 'Maliebaan',
            'customerHousenumber' => 2,
            'customerZipcode' => '8901MN',
            'customerCity' => 'Amersfoort',
            'status' => 'Submitted',
            'dimensions' => '90x70x50',
            'weight' => '2900',
            'trackandtracecode' => Str::random(20),
        ]);

        Package::create([
            'webshopName' => 'Books Galore',
            'webshopStreet' => 'Lange Poten',
            'webshopHousenumber' => 11,
            'webshopZipcode' => '7994CS',
            'webshopCity' => 'Groningen',
            'customerName' => 'Daniel Rodriguez',
            'customerEmail' => 'daniel.rodriguez@email.com',
            'customerStreet' => 'Keizersgracht',
            'customerHousenumber' => 88,
            'customerZipcode' => '5678CD',
            'customerCity' => 'Amsterdam',
            'status' => 'Submitted',
            'dimensions' => '50x50x50',
            'weight' => '1000',
            'trackandtracecode' => Str::random(20),
        ]);

        Package::create([
            'webshopName' => 'Books Galore',
            'webshopStreet' => 'Lange Poten',
            'webshopHousenumber' => 11,
            'webshopZipcode' => '7994CS',
            'webshopCity' => 'Groningen',
            'customerName' => 'Elizabeth Brown',
            'customerEmail' => 'elizabeth.brown@email.com',
            'customerStreet' => 'Wagenstraat',
            'customerHousenumber' => 10,
            'customerZipcode' => '6789GH',
            'customerCity' => 'Utrecht',
            'status' => 'Submitted',
            'dimensions' => '40x30x20',
            'weight' => '2500',
            'trackandtracecode' => Str::random(20),
        ]);

        Package::create([
            'webshopName' => 'Books Galore',
            'webshopStreet' => 'Lange Poten',
            'webshopHousenumber' => 11,
            'webshopZipcode' => '7994CS',
            'webshopCity' => 'Groningen',
            'customerName' => 'Joseph Wilson',
            'customerEmail' => 'joseph.wilson@email.com',
            'customerStreet' => 'Zadelstraat',
            'customerHousenumber' => 25,
            'customerZipcode' => '7890IJ',
            'customerCity' => 'Utrecht',
            'status' => 'Submitted',
            'dimensions' => '80x60x40',
            'weight' => '2000',
            'trackandtracecode' => Str::random(20),
        ]);

        Package::create([
            'webshopName' => 'Books Galore',
            'webshopStreet' => 'Lange Poten',
            'webshopHousenumber' => 11,
            'webshopZipcode' => '7994CS',
            'webshopCity' => 'Groningen',
            'customerName' => 'Abigail Thomas',
            'customerEmail' => 'abigail.thomas@email.com',
            'customerStreet' => 'Willemsparkweg',
            'customerHousenumber' => 23,
            'customerZipcode' => '4512BC',
            'customerCity' => 'Amsterdam',
            'status' => 'Submitted',
            'dimensions' => '120x80x60',
            'weight' => '1000',
            'trackandtracecode' => Str::random(20),
        ]);

        Package::create([
            'webshopName' => 'Books Galore',
            'webshopStreet' => 'Lange Poten',
            'webshopHousenumber' => 11,
            'webshopZipcode' => '7994CS',
            'webshopCity' => 'Groningen',
            'customerName' => 'David Jackson',
            'customerEmail' => 'david.jackson@email.com',
            'customerStreet' => 'Kerkstraat',
            'customerHousenumber' => 45,
            'customerZipcode' => '5678CD',
            'customerCity' => 'Utrecht',
            'status' => 'Submitted',
            'dimensions' => '80x60x40',
            'weight' => '1500',
            'trackandtracecode' => Str::random(20),
        ]);

        Package::create([
            'webshopName' => 'Books Galore',
            'webshopStreet' => 'Lange Poten',
            'webshopHousenumber' => 11,
            'webshopZipcode' => '7994CS',
            'webshopCity' => 'Groningen',
            'customerName' => 'Victoria Perez',
            'customerEmail' => 'victoria.perez@email.com',
            'customerStreet' => 'Coolsingel',
            'customerHousenumber' => 30,
            'customerZipcode' => '9012EF',
            'customerCity' => 'Rotterdam',
            'status' => 'Submitted',
            'dimensions' => '120x100x80',
            'weight' => '2500',
            'trackandtracecode' => Str::random(20),
        ]);

        Package::create([
            'webshopName' => 'Books Galore',
            'webshopStreet' => 'Lange Poten',
            'webshopHousenumber' => 11,
            'webshopZipcode' => '7994CS',
            'webshopCity' => 'Groningen',
            'customerName' => 'Alexander Garcia',
            'customerEmail' => 'alexander.garcia@email.com',
            'customerStreet' => 'Nieuwe Binnenweg',
            'customerHousenumber' => 60,
            'customerZipcode' => '3456GH',
            'customerCity' => 'Den Haag',
            'status' => 'Submitted',
            'dimensions' => '100x80x60',
            'weight' => '2000',
            'trackandtracecode' => Str::random(20),
        ]);

        Package::create([
            'webshopName' => 'Books Galore',
            'webshopStreet' => 'Lange Poten',
            'webshopHousenumber' => 11,
            'webshopZipcode' => '7994CS',
            'webshopCity' => 'Groningen',
            'customerName' => 'Natalie Anderson',
            'customerEmail' => 'natalie.anderson@email.com',
            'customerStreet' => 'Vismarkt',
            'customerHousenumber' => 15,
            'customerZipcode' => '6789KL',
            'customerCity' => 'Groningen',
            'status' => 'Submitted',
            'dimensions' => '120x80x40',
            'weight' => '1700',
            'trackandtracecode' => Str::random(20),
        ]);

        Package::create([
            'webshopName' => 'Electroshop',
            'webshopStreet' => 'Keizersgracht',
            'webshopHousenumber' => 10,
            'webshopZipcode' => '3842LM',
            'webshopCity' => 'Amsterdam',
            'customerName' => 'Christopher Wright',
            'customerEmail' => 'christopher.wright@email.com',
            'customerStreet' => 'Beatrixlaan',
            'customerHousenumber' => 12,
            'customerZipcode' => '5678MN',
            'customerCity' => 'Den Haag',
            'status' => 'Submitted',
            'dimensions' => '60x80x100',
            'weight' => '1000',
            'trackandtracecode' => Str::random(20),
        ]);

        Package::create([
            'webshopName' => 'Electroshop',
            'webshopStreet' => 'Keizersgracht',
            'webshopHousenumber' => 10,
            'webshopZipcode' => '3842LM',
            'webshopCity' => 'Amsterdam',
            'customerName' => 'Grace Davis',
            'customerEmail' => 'grace.davis@email.com',
            'customerStreet' => 'Laan van Westenenk',
            'customerHousenumber' => 25,
            'customerZipcode' => '3456RS',
            'customerCity' => 'Apeldoorn',
            'status' => 'Submitted',
            'dimensions' => '80x60x120',
            'weight' => '1500',
            'trackandtracecode' => Str::random(20),
        ]);

        Package::create([
            'webshopName' => 'Electroshop',
            'webshopStreet' => 'Keizersgracht',
            'webshopHousenumber' => 10,
            'webshopZipcode' => '3842LM',
            'webshopCity' => 'Amsterdam',
            'customerName' => 'Anthony Hernandez',
            'customerEmail' => 'anthony.hernandez@email.com',
            'customerStreet' => 'Oude Kijk in Het Jatstraat',
            'customerHousenumber' => 21,
            'customerZipcode' => '8910KL',
            'customerCity' => 'Groningen',
            'status' => 'Submitted',
            'dimensions' => '100x80x80',
            'weight' => '2000',
            'trackandtracecode' => Str::random(20),
        ]);

        Package::create([
            'webshopName' => 'Electroshop',
            'webshopStreet' => 'Keizersgracht',
            'webshopHousenumber' => 10,
            'webshopZipcode' => '3842LM',
            'webshopCity' => 'Amsterdam',
            'customerName' => 'Avery Scott',
            'customerEmail' => 'avery.scott@email.com',
            'customerStreet' => 'Grote Marktstraat',
            'customerHousenumber' => 17,
            'customerZipcode' => '7994CS',
            'customerCity' => 'Den Haag',
            'status' => 'Submitted',
            'dimensions' => '80x100x60',
            'weight' => '2300',
            'trackandtracecode' => Str::random(20),
        ]);

        Package::create([
            'webshopName' => 'Electroshop',
            'webshopStreet' => 'Keizersgracht',
            'webshopHousenumber' => 10,
            'webshopZipcode' => '3842LM',
            'webshopCity' => 'Amsterdam',
            'customerName' => 'Matthew Taylor',
            'customerEmail' => 'matthew.taylor@email.com',
            'customerStreet' => 'Plein 1945',
            'customerHousenumber' => 6,
            'customerZipcode' => '4567FG',
            'customerCity' => 'Eindhoven',
            'status' => 'Submitted',
            'dimensions' => '100x100x100',
            'weight' => '2500',
            'trackandtracecode' => Str::random(20),
        ]);

        Package::create([
            'webshopName' => 'Electroshop',
            'webshopStreet' => 'Keizersgracht',
            'webshopHousenumber' => 10,
            'webshopZipcode' => '3842LM',
            'webshopCity' => 'Amsterdam',
            'customerName' => 'Sofia Green',
            'customerEmail' => 'sofia.green@email.com',
            'customerStreet' => 'Zandvoorterweg',
            'customerHousenumber' => 7,
            'customerZipcode' => '2106LC',
            'customerCity' => 'Heemstede',
            'status' => 'Submitted',
            'dimensions' => '120x80x40',
            'weight' => '800',
            'trackandtracecode' => Str::random(20),
        ]);

        Package::create([
            'webshopName' => 'Electroshop',
            'webshopStreet' => 'Keizersgracht',
            'webshopHousenumber' => 10,
            'webshopZipcode' => '3842LM',
            'webshopCity' => 'Amsterdam',
            'customerName' => 'Joshua Clark',
            'customerEmail' => 'joshua.clark@email.com',
            'customerStreet' => 'Rijswijkstraat',
            'customerHousenumber' => 141,
            'customerZipcode' => '1062EC',
            'customerCity' => 'Amsterdam',
            'status' => 'Submitted',
            'dimensions' => '80x60x60',
            'weight' => '1500',
            'trackandtracecode' => Str::random(20),
        ]);

        Package::create([
            'webshopName' => 'Electroshop',
            'webshopStreet' => 'Keizersgracht',
            'webshopHousenumber' => 10,
            'webshopZipcode' => '3842LM',
            'webshopCity' => 'Amsterdam',
            'customerName' => 'Madison King',
            'customerEmail' => 'madison.king@email.com',
            'customerStreet' => 'De Lairessestraat',
            'customerHousenumber' => 157,
            'customerZipcode' => '1075HH',
            'customerCity' => 'Amsterdam',
            'status' => 'Submitted',
            'dimensions' => '100x60x80',
            'weight' => '1100',
            'trackandtracecode' => Str::random(20),
        ]);

        Package::create([
            'webshopName' => 'Electroshop',
            'webshopStreet' => 'Keizersgracht',
            'webshopHousenumber' => 10,
            'webshopZipcode' => '3842LM',
            'webshopCity' => 'Amsterdam',
            'customerName' => 'Andrew Baker',
            'customerEmail' => 'andrew.baker@email.com',
            'customerStreet' => 'Korte Vijverberg',
            'customerHousenumber' => 4,
            'customerZipcode' => '2513AB',
            'customerCity' => 'Den Haag',
            'status' => 'Submitted',
            'dimensions' => '120x100x60',
            'weight' => '2200',
            'trackandtracecode' => Str::random(20),
        ]);

        Package::create([
            'webshopName' => 'Electroshop',
            'webshopStreet' => 'Keizersgracht',
            'webshopHousenumber' => 10,
            'webshopZipcode' => '3842LM',
            'webshopCity' => 'Amsterdam',
            'customerName' => 'Lily Cooper',
            'customerEmail' => 'lily.cooper@email.com',
            'customerStreet' => 'Lange Voorhout',
            'customerHousenumber' => 34,
            'customerZipcode' => '2514EG',
            'customerCity' => 'Den Haag',
            'status' => 'Submitted',
            'dimensions' => '80x80x80',
            'weight' => '2000',
            'trackandtracecode' => Str::random(20),
        ]);

        Package::create([
            'webshopName' => 'Electroshop',
            'webshopStreet' => 'Keizersgracht',
            'webshopHousenumber' => 10,
            'webshopZipcode' => '3842LM',
            'webshopCity' => 'Amsterdam',
            'customerName' => 'Evelyn White',
            'customerEmail' => 'evelyn.white@email.com',
            'customerStreet' => 'Oudegracht',
            'customerHousenumber' => 25,
            'customerZipcode' => '3456IJ',
            'customerCity' => 'Groningen',
            'status' => 'Submitted',
            'dimensions' => '120x80x60',
            'weight' => '1900',
            'trackandtracecode' => Str::random(20),
        ]);

        Package::create([
            'webshopName' => 'Electroshop',
            'webshopStreet' => 'Keizersgracht',
            'webshopHousenumber' => 10,
            'webshopZipcode' => '3842LM',
            'webshopCity' => 'Amsterdam',
            'customerName' => 'Nicholas Adams',
            'customerEmail' => 'nicholas.adams@email.com',
            'customerStreet' => 'Lange Poten',
            'customerHousenumber' => 10,
            'customerZipcode' => '6822FV',
            'customerCity' => 'Amsterdam',
            'status' => 'Submitted',
            'dimensions' => '90x70x50',
            'weight' => '2300',
            'trackandtracecode' => Str::random(20),
        ]);
    }
}
